
server:
  port : 8080
  
serviceurl:
  customer: https://tesodev-be-customerservice.herokuapp.com
  order: https://tesodev-be-orderservice.herokuapp.com
  
jwt: 
  secret : tesodev.gateway
  username : tesodev
  password : $2a$12$Xtf43/1V5/yg3dUUxl20I.oyfanLwId8fKqn0LV0vTo/h4C8FQI7O 

